# Generated by Django 3.1.1 on 2020-11-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('historial', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(choices=[('LI', 'Lejos Izquierda'), ('LD', 'Lejos Derecha'), ('CI', 'Cerca Izquierda'), ('CD', 'Cerca Derecha')], max_length=2)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pacientes', verbose_name='DNI Paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profesionales', verbose_name='DNI del Profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_de_compra', models.DateTimeField()),
                ('subtotal', models.FloatField()),
                ('tipo_pago', models.CharField(choices=[('TC', 'Tarjeta de credito'), ('TD', 'Tarjeta de debito'), ('BV', 'Billetera virtual'), ('EF', 'Efectivo')], max_length=2)),
                ('estado_pedido', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pedido', 'Pedido'), ('Taller', 'Taller'), ('Finalizado', 'Finalizado')], max_length=10)),
                ('vendedor', models.CharField(max_length=30)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pacientes', verbose_name='DNI Paciente Comprador')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.productos', verbose_name='ID del Producto')),
            ],
        ),
    ]
