# Generated by Django 3.1.1 on 2020-11-29 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dni', models.IntegerField()),
                ('historial', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(choices=[('LI', 'Lejos Izquierda'), ('LD', 'Lejos Derecha'), ('CI', 'Cerca Izquierda'), ('CD', 'Cerca Derecha')], max_length=2)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('armazon', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asistencia', models.BooleanField(default=False, verbose_name='Asistió al Turno ')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pacientes', verbose_name='Paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profesionales', verbose_name='Profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_de_compra', models.DateTimeField(auto_now_add=True)),
                ('tipo_pago', models.CharField(choices=[('Tarjeta de credito', 'Tarjeta de credito'), ('Tarjeta de debito', 'Tarjeta de debito'), ('Billetera virtual', 'Billetera virtual'), ('Efectivo', 'Efectivo')], max_length=18)),
                ('estado_pedido', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pedido', 'Pedido'), ('Taller', 'Taller'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=10)),
                ('comprador', models.ForeignKey(default='Cliente', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.pacientes', verbose_name='Paciente Comprador')),
                ('producto', models.ForeignKey(default='No disponible', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.productos', verbose_name='Producto')),
                ('vendedor', models.ForeignKey(default='Vendedor', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
