# Generated by Django 3.1.1 on 2020-11-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='dni',
            field=models.IntegerField(max_length=8),
        ),
    ]
