# Generated by Django 3.1.1 on 2020-11-18 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='armazon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turnos',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='historial',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='comprador',
            field=models.ForeignKey(default='Cliente', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.pacientes', verbose_name='DNI Paciente Comprador'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_de_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='producto',
            field=models.ForeignKey(default='No disponible', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.productos', verbose_name='ID del Producto'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='vendedor',
            field=models.ForeignKey(default='Vendedor', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
