# Generated by Django 3.1.1 on 2020-11-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='es_lente',
            field=models.BooleanField(default=False),
        ),
    ]
