# Generated by Django 3.1.1 on 2020-11-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201118_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='paciente',
        ),
        migrations.AddField(
            model_name='turnos',
            name='dni',
            field=models.IntegerField(default=12345678),
        ),
    ]
