# Generated by Django 3.1.1 on 2020-11-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201127_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
