# Generated by Django 3.1.1 on 2020-11-19 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201118_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profesionales',
            name='nombre',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='asistencia',
            field=models.BooleanField(default=False, verbose_name='Asistió al Turno'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='dni',
            field=models.IntegerField(default=12345678, verbose_name='DNI del Paciente'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profesionales', verbose_name='Profesional'),
        ),
    ]
