# Generated by Django 3.1.1 on 2020-12-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201201_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='armazon',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='productos',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('LI', 'Lejos Izquierda'), ('LD', 'Lejos Derecha'), ('CI', 'Cerca Izquierda'), ('CD', 'Cerca Derecha')], max_length=2),
        ),
    ]
