# Generated by Django 3.1.1 on 2020-12-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201201_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='historial',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
